name: Build and release ISO

on:
  workflow_dispatch:
  push:
    branches-ignore: []
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-container:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag build:latest
      - name: Save Docker image as artifact
        run: docker save build:latest -o build-latest.tar
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-latest-image
          path: build-latest.tar

  build-iso:
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: build-latest-image
      - name: Load Docker image
        run: docker load -i build-latest.tar
      - name: Run container and build ISO
        run: |
          docker run --volume ${{ github.workspace }}:/repo --privileged --name build build:latest
          mv live-image-amd64.iso rTS_RescueMedia.iso
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: rTS_RescueMedia
          path: ./rTS_RescueMedia.iso

  tag-upload-release:
    needs: build-iso
    if: github.ref == 'refs/heads/master' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download ISO artifact
        uses: actions/download-artifact@v4
        with:
          name: rTS_RescueMedia
      - name: Tag the repository
        id: tag
        run: |
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git config user.name "GitHub Action"
          git config user.email "admin@rtech.support"
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG
      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          files: ./rTS_RescueMedia.iso
          prerelease: false
          tag_name: ${{ steps.tag.outputs.tag }}
          generate_release_notes: true
      - name: Release new Version
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./rTS_RescueMedia.iso
          generate_release_notes: true

  upload-testing:
    needs: build-iso
    if: github.ref != 'refs/heads/master' && github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download ISO artifact
        uses: actions/download-artifact@v4
        with:
          name: rTS_RescueMedia
      - name: Upload testing release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          files: ./rTS_RescueMedia.iso
          name: testing
          prerelease: true
          tag_name: testing
          generate_release_notes: true
      - name: Release new Version
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./rTS_RescueMedia.iso
          generate_release_notes: true
